# Generated by Django 4.0.1 on 2022-03-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ads_image_alter_ads_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='category_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.RESTRICT, to='ads.categories'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Админ')], default='member', max_length=100),
        ),
    ]
